export const ACTION_TYPES = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_DELETED: 'TASK_DELETED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  ASSIGNMENT_CHANGED: 'ASSIGNMENT_CHANGED',
} as const;

export type ActionType = (typeof ACTION_TYPES)[keyof typeof ACTION_TYPES];
